on:
  push:
    branches:
      - main
jobs: 
 
 Deploy:
      runs-on: ubuntu-latest
      needs: Build
      steps:
        - name: Conexão com o Cluster Kubernets
          uses: matootie/dokube@v1.3.4
          with:
              personalAccessToken:  ${{ secrets.TOKEN_ONECATALOG_KUBERNETS }}
              clusterName:  ${{ secrets.CLUSTER_ID }} 
              expirationTime: "1200"
        - name : Dowloand das depedências de devops para o build da nova imagem.
          run : sudo apt-get install -y git && git clone https://github.com/albuquerquealdry/devops-.git 
        - name: Kubernets Deploy 
          run: kubectl create namespace monitoring
