on:
  push:
    branches:
      - main
jobs:
  Merge:
    runs-on: ubuntu-latest
    steps:
        - name: Conexão com o Cluster Kubernets
          uses: matootie/dokube@v1.3.4
          with:
              personalAccessToken:  325d80a785fada74009b28bb27f6f2db4a4a490b75eff6a82306b35d343fb785
              clusterName:  k8s-1-21-5-do-0-sfo3-1643064513184
              expirationTime: "1200"
        - name : Dowloand das depedências de devops para o build da nova imagem.
          run : sudo apt-get install -y git && git clone https://github.com/albuquerquealdry/devops-.git 
        - name: Kubernets Deploy 
          run: kubectl create namespace monitoring
